### PR TITLE
[3] setup project builds

### LINKED ISSUE #2: Setup production builds
There is a script that creates esm and cjs builds. 
The esm is not working properly.
I'm not sure how it should be done that when a developer installs the package, the right build (esm/cjs) will be used.

### LINKED ISSUE #3: Setup developer flow for node
Instead using tsc every time you made changes to node scripts, set up something like 'hot-reload'
Some ideas in the link below:
https://blog.logrocket.com/configuring-nodemon-with-typescript/

Fix prettier options, and make them the same all over the project.
Add husky and in pre-commit hook run linter/formatter.

### PR DESCRIPTION
**Pull request by Willo0ow**
close #2 
close #3

### CODE REVIEW

File: lib/formatWithPrettier.ts [hunk 1]
```diff
@@ -0,0 +1,19 @@
+import prettier from 'prettier';
+import fs from 'fs';
+
+const prettierOptions = {
+  semi: true,
+  singleQuote: true,
+  jsxBracketSameLine: false,
+  printWidth: 80,
+  tabWidth: 2,
+  useTabs: false
```
Comment (martaqh) [inline lib/formatWithPrettier.ts]: I just thought to share with you my favourite prettier options -- maybe you find something useful for you 😺 
```
  "useTabs": false,
  "tabWidth": 2,
  "singleQuote": true,
  "trailingComma": "all",
  "semi": true,
  "printWidth": 120,
  "bracketSpacing": true
```

**Review by martaqh — APPROVED** [review]
👍

File: lib/formatWithPrettier.ts (hunk 1 above)
Comment (Willo0ow) [reply lib/formatWithPrettier.ts]: Thanks! I've never paid enough attention to these settings to find my favorite setup, I'll definitely try yours!
